# Generated by Django 5.2.4 on 2025-07-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
